README.md
=> Removed comment about VirtualBox in README.md

README.md, defaults/main.yml
=> Upgraded Helm to version 2.11.0

README.md, defaults/main.yml
=> Updated Helm to 2.12.0

README.md, defaults/main.yml
=> Updated Helm to 2.12.2

README.md, defaults/main.yml
=> Updated Helm to 2.13.0

README.md, defaults/main.yml
=> Updated Helm to 2.13.1

README.md, defaults/main.yml
=> Updated Helm to 2.14.0

README.md, defaults/main.yml
=> Updated Helm to 2.14.1

README.md, defaults/main.yml
=> Updated Helm to 2.14.2

README.md, defaults/main.yml
=> Updated Helm to 2.14.3

README.md, defaults/main.yml
=> Updated Helm to 2.15.1

README.md, defaults/main.yml
=> Updated Helm to 2.15.2

README.md, defaults/main.yml
=> Updated Helm to 2.16.0

README.md, defaults/main.yml, molecule/default/tests/test_role.py
=> Updated Helm to 3.0.0

README.md, defaults/main.yml
=> Updated Helm to 3.0.1

README.md, defaults/main.yml
=> Updated Helm to 3.0.2

README.md, defaults/main.yml
=> Updated Helm to 3.1.0

README.md, defaults/main.yml
=> Updated Helm to 3.1.1

README.md, defaults/main.yml
=> Updated Helm to 3.1.2

tasks/main.yml
Fix get helm version blocking the upgrade as defined in https://github.com/gantsign/ansible_role_helm/issues/44
=> Fix get helm version

README.md, defaults/main.yml
=> Updated Helm to 3.2.0

README.md, defaults/main.yml
=> Updated Helm to 3.2.1

README.md, defaults/main.yml
=> Updated Helm to 3.2.3

README.md, defaults/main.yml
=> Updated Helm to 3.3.1

README.md, defaults/main.yml
=> Updated Helm to 3.3.4

README.md, defaults/main.yml
=> Updated Helm to 3.4.0

README.md, defaults/main.yml
=> Updated Helm to 3.4.1

.github/workflows/ci.yml
To workaround the download limits.
=> Changed workflow to login to Docker Hub

README.md, defaults/main.yml
=> Updated Helm to 3.5.3

README.md, defaults/main.yml
=> Updated Helm to 3.6.0

README.md, defaults/main.yml
=> Updated Helm to 3.6.3

README.md, defaults/main.yml
=> Updated Helm to 3.7.0

README.md, defaults/main.yml
=> Updated Helm to 3.8.0

README.md, defaults/main.yml
=> Updated Helm to 3.8.1

README.md, defaults/main.yml
=> Updated Helm to 3.8.2

README.md, defaults/main.yml
=> Updated Helm to 3.9.0

README.md, defaults/main.yml
=> Updated Helm to 3.9.2

README.md, defaults/main.yml
=> Updated Helm to 3.9.4

README.md, defaults/main.yml
=> Updated Helm to 3.10.0

README.md, defaults/main.yml
=> Updated Helm to 3.10.1

README.md, defaults/main.yml
=> Updated Helm to 3.10.2

README.md, defaults/main.yml
=> Updated Helm to 3.11.2

README.md, defaults/main.yml
=> Updated Helm to 3.12.2

meta/main.yml, molecule/default/converge.yml, tasks/main.yml
In preparation for Molecule upgrade.
=> Fixed Ansible Lint warnings

defaults/main.yml, tasks/main.yml, vars/main.yml
For improved VS Code editing support.
=> Added Ansible modelines

README.md, meta/main.yml, molecule/opensuse/molecule.yml
Keeping up with the latest release.
=> Upgraded openSUSE test version to 15.5
